name = "Polytropes"
uuid = "bbcd0084-d8f5-438f-9872-cc447aef9e5f"
authors = ["Kamillo Ferry <kafe@kafe.dev>"]
version = "0.1.0"

[deps]
Bijections = "e2ed5e7c-b2de-5872-ae92-c73ca462fb04"
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"
